version: '2'
services:
    demostore2-app:
        image: demostore2
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://demostore2-mysql:3306/demostore2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    demostore2-mysql:
        extends:
            file: mysql.yml
            service: demostore2-mysql
